name 'ayte-yandex-disk'
maintainer 'Ayte Labs'
maintainer_email 'ops@ayte.team'
license 'MIT'
description 'Installs/Configures ayte-yandex-disk daemon'
long_description 'Installs/Configures ayte-yandex-disk daemon'
version '0.1.1'
chef_version '>= 13.0'
issues_url 'https://github.com/ayte-io/ayte-yandex-disk/issues'
source_url 'https://github.com/ayte-io/ayte-yandex-disk'
depends 'apt', '>= 7.1.1'
depends 'systemd', '>= 3.2.4'
